# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oo_2Ja9KfZK5YEvlOHL5Uu75wSMoMywL
"""

# Commented out IPython magic to ensure Python compatibility.
#Import libraries
from matplotlib_venn import venn2, venn2_circles, venn2_unweighted
from matplotlib_venn import venn3, venn3_circles
from matplotlib import pyplot as plt
# %matplotlib inline
# defining our venn
v = venn2(subsets=(0,1,1), set_labels = ('Set A', 'Set B'))
# since A ∩ B=A from the given data, there is no portion of the set A that is not common to the set B. Using venn diagrams, we can see that A is a subset of B

# setting color of id 11 to purple
v.get_patch_by_id('11').set_color('red')
v.get_patch_by_id('01').set_color('blue')
#setting label of id 10 to New Text
v.get_label_by_id('10').set_text('')
v.get_label_by_id('01').set_text('')

v.get_label_by_id('11').set_text('A ∩ B=A')
#plot title